bug fixed

diff --git a/.github/workflows/deploy_new_feature.yaml b/.github/workflows/deploy_new_feature.yaml
--- a/.github/workflows/deploy_new_feature.yaml
+++ b/.github/workflows/deploy_new_feature.yaml
@@ -24,7 +24,7 @@ jobs:
 
       - name: Set Image Tag
         id: set-image-tag
-        run: echo "IMAGE_TAG=$(echo ${{ github.sha }})" >> $GITHUB_ENV
+        run: echo "IMAGE_TAG=$(echo $RANDOM)" >> $GITHUB_ENV
 
       - name: Build, Tag, and Push Image to Amazon ECR
         env:
@@ -34,13 +34,13 @@ jobs:
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           # Create or update previous_image_tag.txt
-          echo "PREVIOUS_IMAGE_TAG=$(cat previous_image_tag.txt 2>/dev/null || echo 'latest')" > previous_image_tag.txt
-          echo $IMAGE_TAG >> previous_image_tag.txt
+          #echo "PREVIOUS_IMAGE_TAG=$(cat previous_image_tag.txt 2>/dev/null || echo 'latest')" > previous_image_tag.txt
+          #echo $IMAGE_TAG >> previous_image_tag.txt
 
-      - name: Debug Image Tag File
-        run: |
-          echo "Contents of previous_image_tag.txt:"
-          cat previous_image_tag.txt || echo "File not found"
+      # - name: Debug Image Tag File
+      #   run: |
+      #     echo "Contents of previous_image_tag.txt:"
+      #     cat previous_image_tag.txt || echo "File not found"
 
       - name: Deploy to EKS
         env:
